config/routes.rb
Listify::Application.routes.draw do
  resources :list_records

  resources :connections

  get "home/index"
  get "records" => "records#index"
  get "record" => "records#show", :as => :show_record

  root :to => "home#index"

end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  # GET /connections
  # GET /connections.xml
  def index
    @connections = Database_Connection.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @connections }
    end
  end

  # GET /connections/1
  # GET /connections/1.xml
  def show
    @connection = Database_Connection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @connection }
    end
  end

  # GET /connections/new
  # GET /connections/new.xml
  def new
    @connection = Database_Connection.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @connection }
    end
  end

  # GET /connections/1/edit
  def edit
    @connection = Database_Connection.find(params[:id])
  end

  # POST /connections
  # POST /connections.xml
  def create
    @connection = Database_Connection.new(params[:connection])

    respond_to do |format|
      if @connection.save
        format.html { redirect_to(@connection, :notice => 'Connection was successfully created.') }
        format.xml  { render :xml => @connection, :status => :created, :location => @connection }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @connection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /connections/1
  # PUT /connections/1.xml
  def update
    @connection = Database_Connection.find(params[:id])

    respond_to do |format|
      if @connection.update_attributes(params[:connection])
        format.html { redirect_to(@connection, :notice => 'Connection was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @connection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.xml
  def destroy
    @connection = Database_Connection.find(params[:id])
    @connection.destroy

    respond_to do |format|
      format.html { redirect_to(connections_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/views/connections/_form.html.erb
<%= form_for(@connection, :url => connections_path(@connection)) do |f| %>
  <% if @connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
      <% @connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :adapter %><br />
    <%= f.select :adapter, ['mssql','mysql','postgresql', 'sqlite3'] %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :database %><br />
    <%= f.text_field :database %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<h1>Editing connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @connection %> |
<%= link_to 'Back', connections_path %>

app/views/connections/index.html.erb
<h1>Listing connections</h1>

<table>
  <tr>
    <th>Adapter</th>
    <th>Host</th>
    <th>Username</th>
    <th>Password</th>
    <th>Database</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @connections.each do |connection| %>
  <tr>
    <td><%= connection.adapter %></td>
    <td><%= connection.host %></td>
    <td><%= connection.username %></td>
    <td><%= connection.password %></td>
    <td><%= connection.database %></td>
    <td><%= link_to 'Show', connection_path(connection) %></td>
    <td><%= link_to 'Edit', edit_connection_path(connection) %></td>
    <td><%= link_to 'Destroy', connection_path(connection), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Connection', new_connection_path %>
<%= link_to 'Home', root_path %>

app/views/connections/new.html.erb
<h1>New connection</h1>

<%= render 'form' %>

<%= link_to 'Back', connections_path %>

app/views/connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Adapter:</b>
  <%= @connection.adapter %>
</p>

<p>
  <b>Host:</b>
  <%= @connection.host %>
</p>

<p>
  <b>Username:</b>
  <%= @connection.username %>
</p>

<p>
  <b>Password:</b>
  <%= @connection.password %>
</p>

<p>
  <b>Database:</b>
  <%= @connection.database %>
</p>


<%= link_to 'Edit', edit_connection_path(@connection) %> |
<%= link_to 'Back', connections_path %>