config/routes.rb
Listify::Application.routes.draw do
  resources :list_records

  resources :connections

  get "home/index"
  get "records" => "records#index"
  get "record" => "records#show", :as => :show_record

  root :to => "home#index"

end

app/models/list_record.rb
class ListRecord < ActiveRecord::Base
  belongs_to :db_connection
  belongs_to :user
end

app/controllers/list_records_controller.rb
class ListRecordsController < ApplicationController
  # GET /list_records
  # GET /list_records.xml
  def index
    @list_records = ListRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @list_records }
    end
  end

  # GET /list_records/1
  # GET /list_records/1.xml
  def show
    @list_record = ListRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list_record }
    end
  end

  # GET /list_records/new
  # GET /list_records/new.xml
  def new
    @list_record = ListRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list_record }
    end
  end

  # GET /list_records/1/edit
  def edit
    @list_record = ListRecord.find(params[:id])
  end

  # POST /list_records
  # POST /list_records.xml
  def create
    @list_record = ListRecord.new(params[:list_record])

    respond_to do |format|
      if @list_record.save
        format.html { redirect_to(@list_record, :notice => 'List record was successfully created.') }
        format.xml  { render :xml => @list_record, :status => :created, :location => @list_record }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list_record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /list_records/1
  # PUT /list_records/1.xml
  def update
    @list_record = ListRecord.find(params[:id])

    respond_to do |format|
      if @list_record.update_attributes(params[:list_record])
        format.html { redirect_to(@list_record, :notice => 'List record was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list_record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /list_records/1
  # DELETE /list_records/1.xml
  def destroy
    @list_record = ListRecord.find(params[:id])
    @list_record.destroy

    respond_to do |format|
      format.html { redirect_to(list_records_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/list_records_helper.rb
module ListRecordsHelper
end

app/views/list_records/_form.html.erb
<%= form_for(@list_record) do |f| %>
  <% if @list_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_record.errors.count, "error") %> prohibited this list_record from being saved:</h2>

      <ul>
      <% @list_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_name %><br />
    <%= f.text_field :table_name %>
  </div>
  <div class="field">
    <%= f.label :fields %><br />
    <%= f.text_field :fields %>
  </div>
  <div class="field">
    <% c = Hash.new %>
    <% Database_Connection.where(:user_id => 1).each{|x| c.merge!(x.database => x.id)} %>
    <%= f.label :connection_id %><br />
    <%= f.select :connection_id, c %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.label session[:user] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_records/edit.html.erb
<h1>Editing list_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_record %> |
<%= link_to 'Back', list_records_path %>

app/views/list_records/index.html.erb
<h1>Listing list_records</h1>

<table>
  <tr>
    <th>Table name</th>
    <th>Fields</th>
    <th>Connection</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_records.each do |list_record| %>
  <tr>
    <td><%= list_record.table_name %></td>
    <td><%= list_record.fields %></td>
    <td><%= list_record.connection_id %></td>
    <td><%= list_record.user_id %></td>
    <td><%= link_to 'Show', list_record %></td>
    <td><%= link_to 'Edit', edit_list_record_path(list_record) %></td>
    <td><%= link_to 'Destroy', list_record, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Record/View', new_list_record_path %>
<%= link_to 'Home', root_path %>

app/views/list_records/new.html.erb
<h1>New list_record</h1>

<%= render 'form' %>

<%= link_to 'Back', list_records_path %>

app/views/list_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Table name:</b>
  <%= @list_record.table_name %>
</p>

<p>
  <b>Fields:</b>
  <%= @list_record.fields %>
</p>

<p>
  <b>Connection:</b>
  <%= @list_record.connection_id %>
</p>

<p>
  <b>User:</b>
  <%= @list_record.user_id %>
</p>


<%= link_to 'Edit', edit_list_record_path(@list_record) %> |
<%= link_to 'Back', list_records_path %>