config/routes.rb
Listify::Application.routes.draw do
  resources :list_records

  resources :connections

  get "home/index"
  get "records" => "records#index"
  get "record" => "records#show", :as => :show_record

  root :to => "home#index"

end

app/models/record.rb
class Record

  def self.all(table_name, fields)
    c = get_connection
#    disconnect!
    c.connection.execute("SELECT #{fields.join(',')} FROM #{table_name.to_s}")
  end

  def self.find(table_name, unique_field, field_value)
    c = get_connection
    c.connection.execute("SELECT * FROM #{table_name.to_s} WHERE #{unique_field}=#{field_value}")
  end

  def self.get_connection
    conn = Database_Connection.first
    new_conn = create_class("Connection#{conn.id}", ActiveRecord::Base)
    new_conn.establish_connection(
        :adapter => conn.adapter || "postgresql",
        :host => conn.host || "localhost",
        :username => conn.username || "postgres",
        :password => conn.password || "qwedsa",
        :database => conn.database || "pg_service_cucumberxxx"
    )
  end

  def self.create_class(class_name, superclass, &block)
    klass = Class.new superclass, &block
    Object.const_set class_name, klass
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.xml
  def index
    rec = ListRecord.find(params['record_id'])
    @table_name = rec.table_name
    @unique_field = 'id'
    @fields = ((rec.fields.split ",").push(@unique_field)).uniq
    @records = Record.all(@table_name, @fields)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @records }
    end
  end

  # GET /records/1
  # GET /records/1.xml
  def show
    @table_name = :users
    @unique_field = 'id'
    @record = Record.find(@table_name, @unique_field, params[@unique_field])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @record }
    end
  end

  # GET /records/new
  # GET /records/new.xml
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.xml
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to(@record, :notice => 'Record was successfully created.') }
        format.xml  { render :xml => @record, :status => :created, :location => @record }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.xml
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to(@record, :notice => 'Record was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @record.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.xml
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to(records_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_name %><br />
    <%= f.text_field :table_name %>
  </div>
  <div class="field">
    <%= f.label :fields %><br />
    <%= f.text_field :fields %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records for <%= @table_name %> </h1>

<table border="1">
  <tr>
      <% @fields.each do |f| %>
      <th><%= f.humanize %></th>
      <% end %>
    <th></th>
  </tr>

  <% @records.each do |record| %>
      <tr>
        <% @fields.each do |f| %>
            <td><%= record[f] %></td>
        <% end %>
        <td><%= link_to "Show", :action=> "show", :controller=> "records", @unique_field => record[@unique_field] %></td>
        <!--<td><= link_to 'Edit', edit_record_path(record) %></td>-->
        <!--<td><= link_to 'Destroy', record, :confirm => 'Are you sure?', :method => :delete %></td>-->
      </tr>
  <% end %>
</table>

<br/>

<!--<= link_to 'New Record', new_record_path %>-->

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Table name:</b>
  <%= @table_name %>
</p>

<p>
  <b>Fields:</b>
  <%= @record.first.inspect %>
</p>


<!--<= link_to 'Edit', edit_record_path(@record) %> |-->
<%= link_to 'Back', records_path %>